name: citynet
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow=2.15.0
  - pip
  - pip:
    - pyyaml
    - tqdm==4.57.0
    - librosa==0.10.1
    - tf_slim==1.1.0
    - matplotlib==3.3.4
